version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/src
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:5.6.36-fpm
    volumes:
      - ./src:/src
      - ./docker/php.conf:/usr/local/etc/php-fpm.d/zz-log.conf