version: '2'

services:
      
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/src
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - phpmyadmin

  php:
    image: php:5.6.36-apache
    ports:
      - "8082:80"
    command: |
        sh -c 'apt-get update \
        && apt-get install -y zlib1g-dev \
        && docker-php-ext-install zip \
        && a2enmod rewrite \
        && docker-php-ext-install mysqli \
        && apache2-foreground'
    volumes:
      - ./src:/src
      - ./src:/var/www/html
      - ./docker/php.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    links:
        - mysql:db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    links:
        - mysql:db
        
  mysql:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=phpwfw
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=phpwfw
      - MYSQL_PASSWORD=1234
    volumes:
      - "./temp/mysql:/var/lib/mysql"