version: '2'

services:
      
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/src
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - phpmyadmin
      - php

  php:
    build:
      context: .
      dockerfile: docker/php-apache-modrewrite-zip/dockerfile
    ports:
      - "8082:80"
    expose:
      - "9000"
    volumes:
      - ./src:/var/www/html
      - ./test:/var/www/html/test
      - ./docker/php.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    links:
        - mysql:db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    links:
        - mysql:db
        
  mysql:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=phpwfw
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=phpwfw
      - MYSQL_PASSWORD=1234
    command: --sql_mode=""
    volumes:
      - "./temp/mysql:/var/lib/mysql"